# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute crossentropy loss
#'
#' Loss function
#'
#' @param gt_y NumericMatrix. Element-wise multiplication of ground-truth label and softmax output
#' @return Calculated loss.
#' @export
CELoss <- function(gt_y) {
    .Call('_FullyLight_CELoss', PACKAGE = 'FullyLight', gt_y)
}

