# This script is used to run FullyLight package generation
#
# Created by Kunhong Yu(444447)
# Date: 2022/06/04

library(devtools)
library(roxygen2)

my_package <- '/Users/kunhongyu/Desktop/DSBA/Year1/Semester2/Advanced R/project_temp/code/FullyLight/'
#create_package(my_package)

roxygenise(package.dir = my_package)

devtools::check(my_package)

devtools::install(pkg = my_package, reload = TRUE)

devtools::build(my_package)

devtools::document(pkg = my_package)

# After this NAMESPACE should look like:
#
# Generated by roxygen2: do not edit by hand
# export(CELoss)
# export(Compile)
# export(Evaluate)
# export(Fit)
# export(Model)
# export(Predict)
# import(assertthat)
# import(caret)
# import(factoextra)
# import(ggimage)
# import(ggplot2)
# import(glue)
# import(progress)
# importFrom(Rcpp,sourceCpp)
# useDynLib(FullyLight)

# DESCRIPTION:
# Package: FullyLight
# Title: What the Package Does (One Line, Title Case)
# Version: 0.0.0.9000
# Authors@R: 
#   person("First", "Last", , "first.last@example.com", role = c("aut", "cre"),
#          comment = c(ORCID = "YOUR-ORCID-ID"))
# Description: What the package does (one paragraph).
# License: GPL-2
# Encoding: UTF-8
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 7.1.2
# Imports: glue, progress, factoextra, ggimage, caret, Rcpp, ggplot2, assertthat
# LinkingTo: Rcpp

# Importantly, src should be built manually, which stores all C++ files(*.cpp)

library(FullyLight)
?Model
?Compile
?Fit
?Predict
?Evaluate
?CELoss
?to_categoricalF
?Summary
